## Introduction to Pytorch

### Creating tensors with Pytorch

You can create tensors with Pytorch using the `torch.tensor` function. Alternatively, you can create tensors with random values using the `torch.rand`, `torch.randn`, `torch.zeros`, or `torch.ones` functions.

In [1]:
import torch
import numpy as np

In [2]:
a = torch.tensor([1, 2, 3])  # vector (1D tensor)
b = torch.tensor([4, 5, 6], dtype=torch.float)

In [3]:
a.dtype, b.dtype

(torch.int64, torch.float32)

In [4]:
A = torch.ones(3,2)  # matrix (2D tensor)
print(A)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [5]:
B = torch.zeros(3, 4)
print(B)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [6]:
A.shape, A.size()

(torch.Size([3, 2]), torch.Size([3, 2]))

In [7]:
v = np.array([10, 15, 30]).astype(float)
v = torch.from_numpy(v)
v

tensor([10., 15., 30.], dtype=torch.float64)

In [8]:
v_copy = torch.zeros_like(v)

In [9]:
A = torch.ones(3, 2)
B = 3 * torch.ones(3, 2)
C = A + B
C.dtype, C.shape

(torch.float32, torch.Size([3, 2]))

## Tensor operations

Similar to `numpy` library, there are many tensor operations we can perform. `+`, `*`, `multiply` (element-wise multiplication), `matmul` (`mm` for tensor or matrix multiplication).

In [10]:
torch.multiply(A, B)

tensor([[3., 3.],
        [3., 3.],
        [3., 3.]])

In [11]:
X1 = torch.tensor([[1, 1, 1], [2, 2, 2]], dtype=torch.float)
X2 = torch.tensor([[3, 2, 4], [10, 1, 12]], dtype=torch.float).T

In [12]:
X1.matmul(X2)

tensor([[ 9., 23.],
        [18., 46.]])

In [13]:
X1.mm(X2)

tensor([[ 9., 23.],
        [18., 46.]])

## Neural networks layers and functions

- We can access neural network layers using `torch.nn` (sometimes we use `import torch.nn as nn` to shorten the name). For example, we can create a linear layer with `nn.Linear(10, 3)`. This creates a linear layer that takes input of length 10 and returns output of length 3.
- There are functions related to neural networks in `torch.nn.functional` (we generally use `import torch.nn.functional as F`) such as `relu`, `sigmoid`, `softmax`, 

## Neural network loss function and optimizer