[![Open in Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/biodatlab/deep-learning-skooldio/blob/master/01_intro_to_torch.ipynb)

## Introduction to Pytorch

### Creating tensors with Pytorch

You can create tensors with Pytorch using the `torch.tensor` function. Alternatively, you can create tensors with random values using the `torch.rand`, `torch.randn`, `torch.zeros`, or `torch.ones` functions.

In [1]:
import torch
import numpy as np

In [2]:
a = torch.tensor([1, 2, 3]) # vector (1D tensor)
b = torch.tensor([4, 5, 6], dtype=torch.float)

In [3]:
a.dtype, b.dtype

(torch.int64, torch.float32)

In [4]:
A = torch.ones(3,2)  # matrix (2D tensor)
print(A)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [5]:
B = torch.zeros(3, 4)
print(B)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [6]:
A.shape, A.size()

(torch.Size([3, 2]), torch.Size([3, 2]))

In [7]:
r = torch.arange(10)
print(r)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [8]:
torch.arange(0, 1, 0.05)

tensor([0.0000, 0.0500, 0.1000, 0.1500, 0.2000, 0.2500, 0.3000, 0.3500, 0.4000,
        0.4500, 0.5000, 0.5500, 0.6000, 0.6500, 0.7000, 0.7500, 0.8000, 0.8500,
        0.9000, 0.9500])

In [9]:
v = np.array([10, 15, 30]).astype(float)
v = torch.from_numpy(v)
v

tensor([10., 15., 30.], dtype=torch.float64)

In [10]:
v_copy = torch.zeros_like(v)
print(v_copy)

tensor([0., 0., 0.], dtype=torch.float64)


In [11]:
v_copy_ones = torch.ones_like(v)
print(v_copy_ones)

tensor([1., 1., 1.], dtype=torch.float64)


In [12]:
v_copy_ones.int()

tensor([1, 1, 1], dtype=torch.int32)

In [13]:
v_copy_ones.float()

tensor([1., 1., 1.])

In [14]:
v_copy_ones.dtype

torch.float64

## Tensor operations

Similar to `numpy` library, there are many tensor operations we can perform. `+`, `*`, `multiply` (element-wise multiplication), `matmul` (`mm` for tensor or matrix multiplication).

In [15]:
A = torch.ones(3, 2)
B = 3 * torch.ones(3, 2)
C = A + B
C.dtype, C.shape

(torch.float32, torch.Size([3, 2]))

In [16]:
A = torch.tensor([[1, 2], [3, 4]], dtype=torch.float)
B = torch.tensor([[5, 6], [7, 8]], dtype=torch.float)
print(A)
print(B)

tensor([[1., 2.],
        [3., 4.]])
tensor([[5., 6.],
        [7., 8.]])


In [17]:
torch.multiply(A, B)

tensor([[ 5., 12.],
        [21., 32.]])

In [18]:
A * B

tensor([[ 5., 12.],
        [21., 32.]])

In [19]:
X1 = torch.tensor([[1, 1, 1], [2, 2, 2]], dtype=torch.float)
X2 = torch.tensor([[3, 2, 4], [10, 1, 12]], dtype=torch.float).T

In [20]:
X1.matmul(X2)

tensor([[ 9., 23.],
        [18., 46.]])

In [21]:
X1.mm(X2)

tensor([[ 9., 23.],
        [18., 46.]])

In [22]:
X1 @ X2

tensor([[ 9., 23.],
        [18., 46.]])

In [23]:
torch.cat((A, B), dim=1)

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])

In [24]:
torch.cat((A, B), dim=0)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

In [25]:
torch.vstack((A, B))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

In [26]:
data = torch.ones((1, 3, 3))
data.shape

torch.Size([1, 3, 3])

In [27]:
torch.squeeze(data, 0).shape

torch.Size([3, 3])

In [28]:
data.squeeze(0).shape

torch.Size([3, 3])

In [29]:
# we sometimes add the first dimension as a place holder for batch size
A.unsqueeze(0).shape

torch.Size([1, 2, 2])

In [30]:
Z = torch.tensor([[5, 7], [8, 2]])
print(Z)
Z.add_(1)
print(Z)

tensor([[5, 7],
        [8, 2]])
tensor([[6, 8],
        [9, 3]])


In [31]:
Z.shape

torch.Size([2, 2])

In [32]:
Z.view(-1, 4)

tensor([[6, 8, 9, 3]])

In [33]:
Z.flatten()

tensor([6, 8, 9, 3])

In [34]:
Z.view(4)

tensor([6, 8, 9, 3])

## **Autograd**

One of the most powerful functionality of PyTorch is that it can calculte gradients.

In [35]:
x = torch.tensor(10., requires_grad=True)
f = torch.sum(x * x - 4 * x)
f.backward()
x.grad

tensor(16.)

In [36]:
# in the future
weights = torch.ones(4, requires_grad=True)
loss = weights.sum()
loss.backward()
optimizer = torch.optim.SGD([weights], lr=0.01)
optimizer.step()
optimizer.zero_grad()

In [37]:
weights

tensor([0.9900, 0.9900, 0.9900, 0.9900], requires_grad=True)

## Neural networks layers and functions

- We can access neural network layers using `torch.nn` (sometimes we use `import torch.nn as nn` to shorten the name). For example, we can create a linear layer with `nn.Linear(10, 3)`. This creates a linear layer that takes input of length 10 and returns output of length 3.
- There are functions related to neural networks in `torch.nn.functional` (we generally use `import torch.nn.functional as F`) such as `relu`, `sigmoid`, `softmax`, 

In [28]:
import torch.nn as nn
import torch.nn.functional as F

In [29]:
fc = nn.Linear(10, 5)

In [30]:
x = torch.randn((1, 10))

In [31]:
h = fc(x)

In [32]:
h

tensor([[-0.4649, -0.2173,  0.2823,  0.3205,  0.7949]],
       grad_fn=<AddmmBackward0>)

In [33]:
x = torch.randn((10))
x.shape

torch.Size([10])

In [34]:
x = torch.tensor([-10.])
F.relu(x)

tensor([0.])

In [35]:
x = torch.tensor([0.])
torch.sigmoid(x)

tensor([0.5000])