# **Introduction to Pytorch Tensor**

1. สร้าง tensor 2 ตัวที่มีค่าต่อไปนี้

```
[[14, 6],    [[1, 11],
 [1, 3]]      [2, 3]]
```

จากนั้นหาผลบวกของ tensor 2 ตัวนี้

In [1]:
# เขียนโค้ดต่อจากนี้
import torch

A = torch.tensor([[14, 6], [1, 3]])
B = torch.tensor([[1, 11], [2, 3]])
print(A + B)

tensor([[15, 17],
        [ 3,  6]])


2. สร้าง tensor 2 มิติชนิด `torch.float` 2 ตัวที่มีค่าต่อไปนี้

```
[[3, 4],    [[-2, 11],
 [7, -8]]    [-5, 3]]
```

ใช้ `torch.mm` หรือ `torch.matmul` เพื่อหาผลคูณของ tensor ระหว่างตัวแรกและตัวที่สอง

In [2]:
# เขียนโค้ดต่อจากนี้
A = torch.tensor([[3, 4], [-2, 11]])
B = torch.tensor([[7, -8], [-5, 3]])

# มีหลายตัวเลือกในการเขียน matrix multiplication
print(torch.matmul(A, B))
print(torch.mm(A, B))
print(A.mm(B)) # นิยมมากที่สุด

tensor([[  1, -12],
        [-69,  49]])
tensor([[  1, -12],
        [-69,  49]])
tensor([[  1, -12],
        [-69,  49]])


3. สร้าง tensor ที่มีค่าสุ่มจากการกระจายตัวแบบปกติ (normal distribution) โดยใช้คำสั่ง `torch.randn` ที่มีขนาด `(3, 20, 20)` ทำการเพิ่ม dimension ของ tensor ที่สร้างขึ้นให้มีขนาด `(1, 3, 20, 20)` โดยใช้คำสั่ง `torch.unsqueeze`

In [3]:
torch.manual_seed(42)

# วิธีแรก
X = torch.randn((3, 20, 20))
X = X.unsqueeze(0)
print(X.shape)

# วิธีที่สอง
X = torch.randn((3, 20, 20))
X.unsqueeze_(0) # ใส่ _ หลังจาก method จะเทียบเท่ากับ X = X.unsqueeze(0)
print(X.shape)

torch.Size([1, 3, 20, 20])
torch.Size([1, 3, 20, 20])


4. ทดลองสร้าง tensor ดังต่อไปนี้

``` py
v = torch.ones((3, 1, 10, 10))
v_out = v.view(-1, 100)
```

จากนั้นดูขนาดของมิติของ `v` และ `v_out` ว่ามีขนาดเท่าไหร่

In [4]:
v = torch.ones((3, 1, 10, 10))
v_out = v.view(-1, 100)

print(v.shape)
print(v_out.shape)

torch.Size([3, 1, 10, 10])
torch.Size([3, 100])
